### ISSUE TITLE
移除优化

### ISSUE THREAD

**Issue by fishsoft** [yukuoyuan/YRecycleview#2]
不知道你怎么想的，还是说你直接copy谁的，在移除数据的时候直接通知更新适配器不就行了吗？具体代码：/**
     * 删除一个数据的方法
     *
     * @param position 索引
     */
    // TODO 一定要按照这个方式写,不然会crash,希望你有更好的解决方案
    public void removeData(int position) {
//        notifyItemRemoved(position + 1);
//        if (position != list.size()) {
        /*if (position == 0) {
            //移除第一个数据
            list.remove(position);
            notifyDataSetChanged();
        } else */
        if (0 < position && position < list.size() - 1) {
            //移除最后一个数据
            list.remove(position);
            notifyDataSetChanged();
//            notifyItemRangeChanged(position, list.size());
        }
        /*else {
            list.remove(position);
            notifyItemRangeChanged(position, list.size()*//* - position + 1*//*);
        }*/
//        }
    }

**Comment by yukuoyuan** [comment]
不是为了删除的那个动画效果,我会这么写?,你可以看清需求再说ok?
